(function(){
'use strict';
const state={inited:false,loaded:false,hours:24,report:null,abort:null,charts:{},timer:null};
const $=id=>document.getElementById(id);
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compact=n=>{if(n==null||!Number.isFinite(+n))return '—';n=+n;for(const[d,u]of[[1e9,'B'],[1e6,'M'],[1e3,'k']])if(Math.abs(n)>=d)return(n/d).toFixed(Math.abs(n/d)>=100?0:1).replace(/\.0$/,'')+u;return n.toFixed(Math.abs(n)>=100?0:1).replace(/\.0$/,'')};
const pct=n=>n==null?'—':(+n).toFixed(2)+'%';
const time=ts=>ts?new Date(ts*1000).toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'}):'—';
const shortTime=ts=>new Date(ts*1000).toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const age=s=>s==null?'—':s<90?Math.round(s)+'秒':s<5400?Math.round(s/60)+'分钟':(s/3600).toFixed(1)+'小时';
const chart=id=>{if(!state.charts[id])state.charts[id]=echarts.init($(id));return state.charts[id]};
const noAnim={animation:false,textStyle:{color:'#94a3b8'},grid:{left:58,right:55,top:45,bottom:40},tooltip:{trigger:'axis',confine:true},legend:{textStyle:{color:'#94a3b8'}},xAxis:{type:'time',axisLine:{lineStyle:{color:'#334155'}},axisLabel:{color:'#8090aa'}},yAxis:{type:'value',axisLine:{show:false},splitLine:{lineStyle:{color:'rgba(148,163,184,.12)'}},axisLabel:{color:'#8090aa'}}};

window.capacityActivate=function(){if(!state.inited)init();if(!state.loaded)load();resize();clearInterval(state.timer);state.timer=setInterval(()=>{if(!$('tab-capacity').hidden)load()},60000)};
window.capacityDeactivate=function(){clearInterval(state.timer);state.timer=null};
function init(){state.inited=true;document.querySelectorAll('[data-cap-hours]').forEach(b=>b.addEventListener('click',()=>{state.hours=+b.dataset.capHours;document.querySelectorAll('[data-cap-hours]').forEach(x=>x.classList.toggle('active',x===b));load()}));
  $('capRefresh')?.addEventListener('click',load);$('capReset')?.addEventListener('click',()=>{for(const id of['capGroup','capChannel','capModel'])$(id).value='';load()});
  for(const id of['capGroup','capChannel','capModel'])$(id)?.addEventListener('change',load);
  $('capRankType')?.addEventListener('change',renderRanking);window.addEventListener('resize',resize)}
function resize(){Object.values(state.charts).forEach(c=>c&&c.resize())}
function params(){const q=new URLSearchParams({hours:String(state.hours)});const map={capGroup:'group',capChannel:'channel',capModel:'model'};for(const[id,key]of Object.entries(map)){const v=$(id)?.value;if(v)q.set(key,v)}return q}
async function load(){state.abort?.abort();state.abort=new AbortController();$('capError').innerHTML='';$('capSources').innerHTML='<span>正在读取 Monitor 本地事实…</span>';
  try{const res=await fetch('/capacity/report?'+params(),{headers:{Accept:'application/json'},signal:state.abort.signal});if(res.status===401){location.href='/login';return}const d=await res.json();if(!res.ok)throw new Error(d.error||'请求失败');if(d.enabled===false){renderDisabled();return}state.report=d;state.loaded=true;render()}
  catch(e){if(e.name==='AbortError')return;$('capError').innerHTML='<div class="capacity-alert bad">'+esc(e.message||'本地容量事实暂时无法读取')+'；其他 Monitor 页面不受影响。</div>'; $('capSources').innerHTML=''}}
function renderDisabled(){$('capError').innerHTML='<div class="capacity-alert">容量规划默认关闭。验收通过后设置 <code>MONITOR_CAPACITY_ENABLED=true</code> 开放本地只读页；关闭时不运行 worker、不执行查询。</div>';$('capSources').innerHTML='';$('capKpis').innerHTML='';for(const id of['capTrafficChart','capIngressChart','capInfraChart'])state.charts[id]?.clear();$('capRanking').innerHTML='<div class="capacity-empty">功能未启用</div>';$('capComponents').innerHTML='<div class="capacity-empty">功能未启用</div>'}
function render(){const d=state.report;renderSources(d.meta.sources||{});renderKPIs(d);renderFilters(d.options||{});renderTraffic(d);renderIngress(d.ingress||[]);renderInfra(d.infra||[]);renderRanking();renderComponents(d.components||[]);$('capRangeMeta').textContent=time(d.meta.from_ts)+' 至 '+time(d.meta.to_ts)+' · '+Math.round(d.meta.bucket_seconds/60)+'分钟/格';$('capEconomics').querySelector('span').textContent=d.economics?.note||'待成本模块接入。';setTimeout(resize,30)}
function renderSources(src){const names={business_log:'业务日志',pre_route_rejection:'前置拒绝',nginx_ingress:'Nginx 入口',infrastructure:'服务资源'};$('capSources').innerHTML=Object.entries(names).map(([k,name])=>{const s=src[k]||{},cls=s.available?'ok':s.configured?'warn':'bad';return`<span class="capacity-source ${cls}" title="${esc(s.note||'')}">${esc(name)}：${s.available?'可用 · 延时'+age(s.age_sec):s.configured?'暂无数据':'未配置'}</span>`}).join('')}
function renderKPIs(d){const s=d.summary||{},rejectOK=!!d.meta?.sources?.pre_route_rejection?.available,scope=rejectOK?'日志 + 前置拒绝':'仅日志；前置拒绝证据不可用',observed=s.current_at?time(s.current_at):'暂无样本';const cards=[['最新观测业务 RPM',compact(s.current_business_rpm),observed+' · '+scope],['分钟峰值 RPM',compact(s.peak_business_rpm),s.peak_at?time(s.peak_at):'—'],['最新观测 TPM',compact(s.current_tpm),observed],['分钟峰值 TPM',compact(s.peak_tpm),'不被粗粒度均值淹没'],['成功请求占用估算',compact(s.peak_concurrency),'仅成功日志处理时长 / 60秒，不等同真实并发'],['日志稳定率',pct(s.stability_pct),rejectOK?'成功日志 / (日志+前置拒绝)':'仅日志口径；不代表用户侧最终感知']];$('capKpis').innerHTML=cards.map(x=>`<div class="capacity-kpi"><small>${x[0]}</small><b>${x[1]}</b><span>${esc(x[2])}</span></div>`).join('')}
function renderFilters(src){const configs=[['capGroup',src.groups,'全部分组'],['capChannel',src.channels,'全部渠道'],['capModel',src.models,'全部模型']];for(const[id,rows,all]of configs){const el=$(id),value=el.value;const opts=(rows||[]).map(x=>`<option value="${esc(x.key)}">${esc(x.label)}</option>`).join('');el.innerHTML=`<option value="">${all}</option>`+opts;if([...el.options].some(o=>o.value===value))el.value=value}}
function renderTraffic(d){const pts=d.series||[],data=k=>pts.map(p=>[p.ts*1000,p[k]]);const c=chart('capTrafficChart');c.setOption({...noAnim,legend:{...noAnim.legend,data:['业务 RPM','日志 RPM','前置拒绝 RPM','TPM','日志稳定率']},yAxis:[{...noAnim.yAxis,name:'RPM / TPM'},{...noAnim.yAxis,name:'日志稳定率',min:0,max:100,axisLabel:{color:'#8090aa',formatter:'{value}%'}}],series:[line('业务 RPM',data('business_rpm'),'#818cf8'),line('日志 RPM',data('logged_rpm'),'#38bdf8'),line('前置拒绝 RPM',data('rejected_rpm'),'#fb7185'),line('TPM',data('tpm'),'#f59e0b'),{...line('日志稳定率',data('stability_pct'),'#34d399'),yAxisIndex:1}]},true)}
function line(name,data,color){return{name,type:'line',data,showSymbol:false,connectNulls:false,smooth:false,lineStyle:{width:1.8,color},itemStyle:{color},areaStyle:name==='业务 RPM'?{color:'rgba(129,140,248,.08)'}:undefined}}
function renderIngress(rows){const nodes=[...new Set(rows.map(x=>x.node))],colors=['#60a5fa','#a78bfa','#34d399','#f59e0b'],series=[];for(const[n,i]of nodes.map((n,i)=>[n,i])){const own=rows.filter(x=>x.node===n),color=colors[i%colors.length];series.push(line(n+' RPM',own.map(x=>[x.ts*1000,x.rpm]),color));series.push({...line(n+' 入口总占用',own.map(x=>[x.ts*1000,x.estimated_inflight]),color),yAxisIndex:1,lineStyle:{width:1,type:'solid',color}});series.push({...line(n+' 代理上游占用',own.map(x=>[x.ts*1000,x.estimated_upstream_inflight]),color),yAxisIndex:1,lineStyle:{width:1,type:'dashed',color}})}const c=chart('capIngressChart');if(!rows.length){c.clear();c.setOption({title:{text:'入口事实未启用或暂无数据',left:'center',top:'middle',textStyle:{color:'#64748b',fontSize:12}}});return}c.setOption({...noAnim,legend:{...noAnim.legend,type:'scroll',data:series.map(x=>x.name)},yAxis:[{...noAnim.yAxis,name:'RPM'},{...noAnim.yAxis,name:'估算在途请求'}],series},true)}
function renderInfra(rows){const interesting=rows.filter(x=>['cpu','connections','disk_queue','resp_ms'].includes(x.metric)),keys=[...new Set(interesting.map(x=>x.resource+' · '+x.metric))].slice(0,8),series=keys.map((key,i)=>{const[r,m]=key.split(' · ');return line(key,interesting.filter(x=>x.resource===r&&x.metric===m).map(x=>[x.ts*1000,x.value]),['#34d399','#60a5fa','#f59e0b','#fb7185','#a78bfa','#22d3ee'][i%6])});const c=chart('capInfraChart');if(!series.length){c.clear();c.setOption({title:{text:'资源采样未启用或暂无数据',left:'center',top:'middle',textStyle:{color:'#64748b',fontSize:12}}});return}c.setOption({...noAnim,legend:{...noAnim.legend,type:'scroll',data:keys},series},true)}
function renderRanking(){const rows=state.report?.breakdowns?.[$('capRankType')?.value||'groups']||[];if(!rows.length){$('capRanking').innerHTML='<div class="capacity-empty">当前筛选范围暂无负载事实</div>';return}$('capRanking').innerHTML='<table class="capacity-table"><thead><tr><th>名称</th><th>请求</th><th>平均 RPM</th><th>平均 TPM</th><th>日志稳定率</th></tr></thead><tbody>'+rows.map(x=>{const scope=x.stability_scope==='log_plus_pre_route'?'日志+前置拒绝':'仅日志';return`<tr><td><span class="capacity-rank-name" title="${esc(x.label)}">${esc(x.label)}</span></td><td>${compact(x.requests)}</td><td>${compact(x.average_rpm)}</td><td>${compact(x.average_tpm)}</td><td title="${scope}">${pct(x.stability_pct)} · ${scope}</td></tr>`}).join('')+'</tbody></table>'}
function renderComponents(rows){if(!rows.length){$('capComponents').innerHTML='<div class="capacity-empty">暂无服务资源证据，不做扩容判断。</div>';return}$('capComponents').innerHTML='<table class="capacity-table"><thead><tr><th>服务/资源</th><th>类型</th><th>状态</th><th>CPU</th><th>容量建议</th><th>数据年龄</th></tr></thead><tbody>'+rows.map(x=>{const advice=x.status==='bad'?'优先排查，评估扩容':x.status==='warn'?'持续观察趋势':x.status==='ok'?'暂无扩容证据':'证据不足';return`<tr><td><span class="capacity-rank-name">${esc(x.name)}</span></td><td>${esc(x.type)}</td><td><span class="capacity-status ${esc(x.status)}">${x.status==='ok'?'正常':x.status==='warn'?'需关注':x.status==='bad'?'异常':'证据不足'}</span></td><td>${x.metrics?.cpu==null?'—':(+x.metrics.cpu).toFixed(1)+'%'}</td><td>${advice}</td><td>${age(x.age_sec)}</td></tr>`}).join('')+'</tbody></table>'}
})();
