package monitor

import (
	"context"
	"encoding/json"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/glebarez/sqlite"
	"gorm.io/gorm"
)

// Opt-in, completely offline acceptance. The evidence file is generated by
// readonly-inspect, whose query already excludes synthetic test traffic.
func TestFinanceGiftScopeRepairRealEvidenceOnLocalClone(t *testing.T) {
	evidencePath := os.Getenv("MONITOR_GIFT_SCOPE_REPAIR_EVIDENCE")
	mainPath := os.Getenv("MONITOR_GIFT_SCOPE_REPAIR_MAIN_SNAPSHOT")
	if evidencePath == "" || mainPath == "" {
		t.Skip("requires private original-log evidence and local main snapshot")
	}
	f, err := os.Open(evidencePath)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	var evidence struct {
		UserID int64 `json:"user_id"`
		Hour   int64 `json:"hour_ts"`
		Rows   []struct {
			ID        int64  `json:"id"`
			UserID    int64  `json:"user_id"`
			CreatedAt int64  `json:"created_at"`
			Type      int    `json:"type"`
			Quota     int64  `json:"quota"`
			Group     string `json:"group"`
		} `json:"rows"`
	}
	decoder := json.NewDecoder(io.LimitReader(f, 1<<20))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&evidence); err != nil {
		t.Fatal(err)
	}
	if evidence.UserID <= 0 || evidence.Hour <= 0 || evidence.Hour%3600 != 0 || len(evidence.Rows) == 0 || len(evidence.Rows) > 100 {
		t.Fatal("invalid bounded evidence")
	}
	db := copyGiftScopeSnapshotForTest(t)
	var target FinanceGiftBoundaryState
	if err := db.Where("hour_ts=? AND user_id=?", evidence.Hour, evidence.UserID).First(&target).Error; err != nil {
		t.Fatal(err)
	}
	ctx := context.Background()
	before, err := loadFinanceGiftScopeSnapshot(ctx, db, target.SourceEpoch, evidence.Hour, evidence.UserID)
	if err != nil {
		t.Fatal(err)
	}
	var cursorsBefore []FinanceFactSyncState
	if err := db.Find(&cursorsBefore).Error; err != nil {
		t.Fatal(err)
	}
	var factsBefore []FinanceUserHourFact
	if err := db.Order("hour_ts,user_id").Find(&factsBefore).Error; err != nil {
		t.Fatal(err)
	}
	source := financeGiftBoundarySource(t)
	for _, row := range evidence.Rows {
		if row.UserID != evidence.UserID || row.CreatedAt < evidence.Hour || row.CreatedAt >= evidence.Hour+3600 {
			t.Fatal("evidence outside requested target")
		}
		// These placeholders are fixture-only SQL classifier scaffolding, not
		// inferred user metadata; exported membership was already classified.
		if _, err := source.Exec("INSERT INTO logs(id,user_id,created_at,type,quota,token_id,token_name,request_id,content,other,`group`) VALUES(?,?,?,?,?,1,'','','','',?)", row.ID, row.UserID, row.CreatedAt, row.Type, row.Quota, row.Group); err != nil {
			t.Fatal(err)
		}
	}
	mainURI := (&url.URL{Scheme: "file", Path: mainPath, RawQuery: "mode=ro&immutable=1"}).String()
	mainDB, err := gorm.Open(sqlite.Open(mainURI), &gorm.Config{})
	if err != nil {
		t.Fatal(err)
	}
	mainConn, err := mainDB.DB()
	if err != nil {
		t.Fatal(err)
	}
	defer mainConn.Close()
	m := &Monitor{storeDB: mainDB, usageFactsDB: db}
	policies, err := loadChannelBusinessGroupPolicies(ctx, mainDB)
	if err != nil {
		t.Fatal(err)
	}
	accounts, err := m.loadFinanceInternalAccounts(ctx)
	if err != nil {
		t.Fatal(err)
	}
	excluded := map[int64]bool{}
	for _, a := range accounts {
		excluded[a.UserID] = true
	}
	seed, err := financeStartHour("2026-05-01")
	if err != nil {
		t.Fatal(err)
	}
	allocationBefore, err := m.loadFinanceGiftAllocationForScope(ctx, seed, evidence.Hour, evidence.Hour+3600, policies, excluded)
	if err != nil {
		t.Fatal(err)
	}
	journal, err := os.OpenFile(filepath.Join(t.TempDir(), "audit.jsonl"), os.O_CREATE|os.O_EXCL|os.O_RDWR, 0600)
	if err != nil {
		t.Fatal(err)
	}
	defer journal.Close()
	encoder := json.NewEncoder(journal)
	audit := func(entry financeGiftScopeBatchEntry) error {
		if err := encoder.Encode(entry); err != nil {
			return err
		}
		return journal.Sync()
	}
	plan := []financeGiftScopeTarget{{target.SourceEpoch, evidence.Hour, evidence.UserID}}
	batch, err := newFinanceGiftScopeBatchRunner(db, source).run(ctx, plan, audit)
	if err != nil || batch.Status != "complete" || len(batch.Entries) != 1 {
		t.Fatalf("batch=%+v err=%v", batch, err)
	}
	repaired := batch.Entries[0]
	if repaired.RowsUpdated != len(evidence.Rows) {
		t.Fatalf("repair=%+v", repaired)
	}
	after, err := loadFinanceGiftScopeSnapshot(ctx, db, target.SourceEpoch, evidence.Hour, evidence.UserID)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(before.UserState, after.UserState) || after.State.ConsumeQuota != before.State.ConsumeQuota || after.State.RefundQuota != before.State.RefundQuota || len(after.Events) != len(before.Events) {
		t.Fatal("monetary proofs changed")
	}
	for _, e := range after.Events {
		if !e.GroupKnown {
			t.Fatal("scope not filled")
		}
	}
	allocationAfter, err := m.loadFinanceGiftAllocationForScope(ctx, seed, evidence.Hour, evidence.Hour+3600, policies, excluded)
	if err != nil {
		t.Fatal(err)
	}
	if allocationBefore.Coverage.ScopeUnknownEvents-allocationAfter.Coverage.ScopeUnknownEvents != int64(repaired.RowsUpdated) {
		t.Fatal("unexpected coverage change")
	}
	// A new runner models a process restart; the persisted facts, not memory
	// or the audit log alone, decide whether a source query is still needed.
	resumed, err := newFinanceGiftScopeBatchRunner(db, nil).run(ctx, plan, audit)
	if err != nil || resumed.Status != "complete" || len(resumed.Entries) != 1 {
		t.Fatalf("resumed=%+v err=%v", resumed, err)
	}
	retry := resumed.Entries[0]
	if retry.RowsUpdated != 0 || retry.ContentHash != repaired.ContentHash {
		t.Fatal("retry changed evidence", err)
	}
	if _, err := journal.Seek(0, io.SeekStart); err != nil {
		t.Fatal(err)
	}
	journalReader := json.NewDecoder(journal)
	for _, expected := range []financeGiftScopeBatchEntry{repaired, retry} {
		var stored financeGiftScopeBatchEntry
		if err := journalReader.Decode(&stored); err != nil || !reflect.DeepEqual(stored, expected) {
			t.Fatal("audit did not persist outcome", err)
		}
	}
	var extra financeGiftScopeBatchEntry
	if err := journalReader.Decode(&extra); err != io.EOF {
		t.Fatal("unexpected duplicate audit entry", err)
	}
	var cursorsAfter []FinanceFactSyncState
	var factsAfter []FinanceUserHourFact
	if err := db.Find(&cursorsAfter).Error; err != nil {
		t.Fatal(err)
	}
	if err := db.Order("hour_ts,user_id").Find(&factsAfter).Error; err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(cursorsBefore, cursorsAfter) || !reflect.DeepEqual(factsBefore, factsAfter) {
		t.Fatal("main cursor or monetary facts changed")
	}
	t.Logf("real evidence matched %d/%d rows; consume_quota=%d refund_quota=%d unchanged; unknown scope %d -> %d; gift complete %t -> %t; verified gift consumption microUSD=%d; retry writes=0", repaired.RowsUpdated, len(evidence.Rows), before.State.ConsumeQuota, before.State.RefundQuota, allocationBefore.Coverage.ScopeUnknownEvents, allocationAfter.Coverage.ScopeUnknownEvents, allocationBefore.Coverage.Complete, allocationAfter.Coverage.Complete, allocationAfter.Allocation.PeriodGiftConsumptionMicroUSD)
}
